/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import { Button, SvgIcon } from '@mui/material';
import { ReactComponent as ArrowForwardFilled1 } from './assets/images/ArrowForwardFilled.svg';
import { styled } from '@mui/material/styles';
import FeedbackBar from './FeedbackBar';
import useFeedbackBarPage from './useFeedbackBarPage';
 
const TypeQuestSidebarOpen = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  display: `flex`,  
  flexDirection: `column`,  
  width: "100vw",  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
});
  
const Page = styled("div")({  
  display: `flex`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  height: `1079px`,  
});
  
const FeedbackBar1 = styled(FeedbackBar)(({ theme }) =>({  
  alignSelf: `stretch`,  
}));
  
const Content = styled("div")({  
  display: `flex`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  flexGrow: `1`,  
});
  
const Sec1 = styled("div")({  
  display: `flex`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `22px 60px 30px 60px`,  
  boxSizing: `border-box`,  
});
  
const HeroContent = styled("div")({  
  display: `flex`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  gap: `117px`,  
  padding: `0px 0px 20px 0px`,  
  boxSizing: `border-box`,  
});
  
const WelcomeRow = styled("div")({  
  display: `flex`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  gap: `40px`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
});
  
const AutoAddedFrame = styled("div")({  
  display: `flex`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  gap: `10px`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  overflow: `hidden`,  
});
  
const Frame1 = styled("div")({  
  display: `flex`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  gap: `10px`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
});
  
const Title = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Inter`,  
  fontWeight: `700`,  
  fontSize: `28px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
});
  
const Description = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Inter`,  
  fontWeight: `400`,  
  fontSize: `18px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
});
  
const Features = styled("div")({  
  display: `flex`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  gap: `8px`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  height: `248px`,  
  width: `814px`,  
});
  
const Feature = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(86, 86, 86, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Inter`,  
  fontWeight: `400`,  
  fontSize: `16px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `26px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
});
  
const Divider = styled("div")({  
  display: `flex`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `6px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  overflow: `hidden`,  
});
  
const Divider1 = styled("div")({  
  display: `flex`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  gap: `6px`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
});
  
const Divider2 = styled("div")({  
  backgroundColor: `rgba(86, 86, 86, 1)`,  
  flexGrow: `1`,  
  height: `1px`,  
});
  
const Feature1 = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(86, 86, 86, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Inter`,  
  fontWeight: `400`,  
  fontSize: `16px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `26px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
});
  
const Divider3 = styled("div")({  
  display: `flex`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `6px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  overflow: `hidden`,  
});
  
const Divider4 = styled("div")({  
  display: `flex`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  gap: `6px`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
});
  
const Divider5 = styled("div")({  
  backgroundColor: `rgba(86, 86, 86, 1)`,  
  flexGrow: `1`,  
  height: `1px`,  
});
  
const Feature2 = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(86, 86, 86, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Inter`,  
  fontWeight: `400`,  
  fontSize: `16px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `26px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
});
  
const Divider6 = styled("div")({  
  display: `flex`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `6px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  overflow: `hidden`,  
});
  
const Divider7 = styled("div")({  
  display: `flex`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  gap: `6px`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
});
  
const Divider8 = styled("div")({  
  backgroundColor: `rgba(86, 86, 86, 1)`,  
  flexGrow: `1`,  
  height: `1px`,  
});
  
const Feature3 = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(86, 86, 86, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Inter`,  
  fontWeight: `400`,  
  fontSize: `16px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `26px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
});
  
const Divider9 = styled("div")({  
  display: `flex`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `6px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  overflow: `hidden`,  
});
  
const Divider10 = styled("div")({  
  display: `flex`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  gap: `6px`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
});
  
const Divider11 = styled("div")({  
  backgroundColor: `rgba(86, 86, 86, 1)`,  
  flexGrow: `1`,  
  height: `1px`,  
});
  
const Feature4 = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(86, 86, 86, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Inter`,  
  fontWeight: `400`,  
  fontSize: `16px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `26px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
});
  
const Next = styled("div")({  
  display: `flex`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  gap: `6px`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
});
 
function FeedbackBarPage() {
  const {fns} = useFeedbackBarPage();
  return (
    <TypeQuestSidebarOpen >
       <Page >
         <FeedbackBar1   />
         <Content >
           <Sec1 >
             <HeroContent >
               <WelcomeRow >
                 <AutoAddedFrame >
                   <Frame1 >
                     <Title >
                       {`Feedback Component`}
                         </Title>
                     <Description >
                       {`This component is .....`}
                         </Description>
                   </Frame1>
                 </AutoAddedFrame>
                 <Features >
                   <Feature >
                     {`Uses variants to show different states on hover`}
                       </Feature>
                   <Divider >
                     <Divider1 >
                       <Divider2 >
                       </Divider2>
                     </Divider1>
                   </Divider>
                   <Feature1 >
                     {`Uses nested menu item with variants to show different states on hover as well`}
                       </Feature1>
                   <Divider3 >
                     <Divider4 >
                       <Divider5 >
                       </Divider5>
                     </Divider4>
                   </Divider3>
                   <Feature2 >
                     {`Is fully responsive to the full height of the parent`}
                       </Feature2>
                   <Divider6 >
                     <Divider7 >
                       <Divider8 >
                       </Divider8>
                     </Divider7>
                   </Divider6>
                   <Feature3 >
                     {`Other thing..`}
                       </Feature3>
                   <Divider9 >
                     <Divider10 >
                       <Divider11 >
                       </Divider11>
                     </Divider10>
                   </Divider9>
                   <Feature4 >
                     {`Other thing..`}
                       </Feature4>
                 </Features>
                 <Next >
                   <Button variant="contained" size="large" color="primary"  onClick={() => fns.navigate("/moonbase/dashboard")} endIcon={ <SvgIcon sx={{width: "18px", height: "22px"}} component = { ArrowForwardFilled1 } />}  > Full Dashboard </Button>
                 </Next>
               </WelcomeRow>
             </HeroContent>
           </Sec1>
         </Content>
       </Page>
     </TypeQuestSidebarOpen>
   );
}

export default FeedbackBarPage;
