/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import { Button, SvgIcon, Link } from '@mui/material';
import { ReactComponent as ArrowForwardFilled1 } from './assets/images/ArrowForwardFilled.svg';
import { styled } from '@mui/material/styles';
import Sidebar from './Sidebar';
import useNavbarPage from './useNavbarPage';
 
const TypeQuestSidebarOpen = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  display: `flex`,  
  flexDirection: `column`,  
  height: `1079px`,  
  width: `1423px`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
});
  
const Page = styled("div")({  
  display: `flex`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  flexGrow: `1`,  
});
  
const Sidebar1 = styled(Sidebar)(({ theme }) =>({  
  alignSelf: `stretch`,  
  width: `90px`,  
}));
  
const Content = styled("div")({  
  display: `flex`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `60px 0px 0px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  flexGrow: `1`,  
});
  
const Sec1 = styled("div")({  
  display: `flex`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `22px 60px 30px 60px`,  
  boxSizing: `border-box`,  
});
  
const HeroContent = styled("div")({  
  display: `flex`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  gap: `117px`,  
  padding: `0px 0px 20px 0px`,  
  boxSizing: `border-box`,  
});
  
const WelcomeRow = styled("div")({  
  display: `flex`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  gap: `40px`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
});
  
const AutoAddedFrame = styled("div")({  
  display: `flex`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  gap: `10px`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  overflow: `hidden`,  
});
  
const Frame1 = styled("div")({  
  display: `flex`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  gap: `10px`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
});
  
const Disclaimer = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Inter`,  
  fontWeight: `600`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  height: `71px`,  
  width: `407px`,  
});
  
const Title = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Inter`,  
  fontWeight: `700`,  
  fontSize: `28px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
});
  
const DescriptionSpan1 = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Inter`,  
  fontWeight: `700`,  
  fontSize: `18px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `28px`,  
  textTransform: `none`,  
});
  
const DescriptionSpan2 = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Inter`,  
  fontWeight: `400`,  
  fontSize: `18px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `28px`,  
  textTransform: `none`,  
});
  
const DescriptionSpan3 = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Inter`,  
  fontWeight: `700`,  
  fontSize: `18px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `28px`,  
  textTransform: `none`,  
});
  
const DescriptionSpan4 = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Inter`,  
  fontWeight: `400`,  
  fontSize: `18px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `28px`,  
  textTransform: `none`,  
});
  
const Description = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: "unset",  
  fontWeight: `400`,  
  fontSize: `18px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `28px`,  
  textTransform: `none`,  
});
  
const Features = styled("div")({  
  display: `flex`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  gap: `8px`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `814px`,  
});
  
const Feature = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Inter`,  
  fontWeight: `700`,  
  fontSize: `16px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `26px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
});
  
const Feature1 = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(86, 86, 86, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Inter`,  
  fontWeight: `400`,  
  fontSize: `16px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `26px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
});
  
const Divider = styled("div")({  
  display: `flex`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `6px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  overflow: `hidden`,  
});
  
const Divider1 = styled("div")({  
  display: `flex`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  gap: `6px`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
});
  
const Divider2 = styled("div")({  
  backgroundColor: `rgba(86, 86, 86, 1)`,  
  flexGrow: `1`,  
  height: `1px`,  
});
  
const Feature2 = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(86, 86, 86, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Inter`,  
  fontWeight: `400`,  
  fontSize: `16px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `26px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
});
  
const Divider3 = styled("div")({  
  display: `flex`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `6px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  overflow: `hidden`,  
});
  
const Divider4 = styled("div")({  
  display: `flex`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  gap: `6px`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
});
  
const Divider5 = styled("div")({  
  backgroundColor: `rgba(86, 86, 86, 1)`,  
  flexGrow: `1`,  
  height: `1px`,  
});
  
const Feature3 = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(86, 86, 86, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Inter`,  
  fontWeight: `400`,  
  fontSize: `16px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `26px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
});
  
const Divider6 = styled("div")({  
  display: `flex`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `6px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  overflow: `hidden`,  
});
  
const Divider7 = styled("div")({  
  display: `flex`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  gap: `6px`,  
  flexGrow: `1`,  
});
  
const Next = styled("div")({  
  display: `flex`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  gap: `6px`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
});
  
const Link1 = styled(Link)(({ theme }) =>({  
  color: theme.palette["Primary"]["Main"],  
  fontStyle: theme.typography["Typography"]["Body 3"].fontStyle,  
  fontFamily: theme.typography["Typography"]["Body 3"].fontFamily,  
  fontWeight: theme.typography["Typography"]["Body 3"].fontWeight,  
  fontSize: theme.typography["Typography"]["Body 3"].fontSize,  
  letterSpacing: theme.typography["Typography"]["Body 3"].letterSpacing,  
  textDecoration: theme.typography["Typography"]["Body 3"].textDecoration,  
  lineHeight: theme.typography["Typography"]["Body 3"].lineHeight,  
  textTransform: theme.typography["Typography"]["Body 3"].textTransform,  
}));
 
function NavbarPage() {
  const {fns} = useNavbarPage();
  return (
    <TypeQuestSidebarOpen >
       <Page >
         <Sidebar1   />
         <Content >
           <Sec1 >
             <HeroContent >
               <WelcomeRow >
                 <AutoAddedFrame >
                   <Frame1 >
                     <Disclaimer >
                       {`*Designed for Desktop only`}
                         </Disclaimer>
                     <Title >
                       {`The interactive Dashboard sample 
is made up of 2 main components:`}
                         </Title>
                     <Description >
                       <DescriptionSpan1  >{`1.`}</DescriptionSpan1>
                       <DescriptionSpan2  >{` Sidebar component
`}</DescriptionSpan2>
                       <DescriptionSpan3  >{`2.`}</DescriptionSpan3>
                       <DescriptionSpan4  >{` Feedback component`}</DescriptionSpan4>
                     </Description>
                   </Frame1>
                 </AutoAddedFrame>
                 <Features >
                   <Feature >
                     {`This interactive Sidebar component:`}
                       </Feature>
                   <Feature1 >
                     {`Uses variants to show different states on hover`}
                       </Feature1>
                   <Divider >
                     <Divider1 >
                       <Divider2 >
                       </Divider2>
                     </Divider1>
                   </Divider>
                   <Feature2 >
                     {`Uses nested menu item with variants to show different states on hover and selected as well`}
                       </Feature2>
                   <Divider3 >
                     <Divider4 >
                       <Divider5 >
                       </Divider5>
                     </Divider4>
                   </Divider3>
                   <Feature3 >
                     {`Is fully responsive to the full height of the parent`}
                       </Feature3>
                   <Divider6 >
                     <Divider7 >
                     </Divider7>
                   </Divider6>
                 </Features>
                 <Next >
                   <Button variant="contained" size="large" color="primary"  onClick={() => fns.navigate("/moonbase/feedbackbar")} endIcon={ <SvgIcon sx={{width: "18px", height: "22px"}} component = { ArrowForwardFilled1 } />}  > See 2nd Component </Button>
                   {false ?
                       <Link1 href="#" underline="hover"  >Go to Feedback component</Link1>
                   :null}
                 </Next>
               </WelcomeRow>
             </HeroContent>
           </Sec1>
         </Content>
       </Page>
     </TypeQuestSidebarOpen>
   );
}

export default NavbarPage;
