/**********************************************************************
*
*   Component hook generated by Quest
*
*   Code Logic for the component goes in this hook
*   To setup bindings that use the data here or call the functions here, use the Quest editor   
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/
import { useState } from "react";




const useDashboard = () => {
  const products = [
  ];

  let [selectedProduct, setSelectedProduct] = useState(null);
  let [showPayment, setShowPayment] = useState(false);

  let data = { products, selectedProduct, showPayment };

  const closePaymentDialog = () => {
    setShowPayment(false);
  }

  const buyClicked = (product) => {
    setSelectedProduct(product);
    setShowPayment(true);
  }

  let fns = { buyClicked, closePaymentDialog };
  return { data, fns };
}

export default useDashboard;