/**********************************************************************
*
*   Component hook generated by Quest
*
*   Code Logic for the component goes in this hook
*   To setup bindings that use the data here or call the functions here, use the Quest editor   
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/
import { ReactComponent as Calendar } from './assets/images/Icon_Calendar__Color_default.svg';
import { ReactComponent as Star } from './assets/images/Icon_Star__Color_default.svg';
import { ReactComponent as Plus } from './assets/images/Icon_Plus__Color_default.svg';


const useEventList = () => {
  let events = [
    {
      index: 0,
      name: "Meet with Ellen Cho",
      location: "Zoom Call",
      icon: Calendar,
      color: "primary",
      frameColor: "#D2D1FF"
    },
    {
      index: 1,
      name: "1-1 with Scott",
      location: "Blue Bottle Coffee",
      icon: Star,
      color: "success",
      frameColor: "#D1FFD6"
    },
    {
      index: 2,
      name: "Figma Webinar",
      location: "Google Meet",
      icon: Plus,
      color: "info",
      frameColor: "#D1FFF4"
    }
  ];

  const formatDate = (date) => {
    let monthNames = ["Jan", "Feb", "Mar", "Apr",
      "May", "Jun", "Jul", "Aug",
      "Sep", "Oct", "Nov", "Dec"];

    let day = date.getDate();

    let monthIndex = date.getMonth();
    let monthName = monthNames[monthIndex];

    let year = date.getFullYear();

    return `${monthName} ${day}, ${year}`;
  }

  let data = {};
  data.events = events;
  data.currentDate = formatDate(new Date());

  let fns = {};
  return { data, fns };
}

export default useEventList;